services:
  - type: web
    name: realtime-language-translator
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3002
    plan: free
